# Generated by Django 3.2.8 on 2021-10-24 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rep', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64, null=True)),
                ('address', models.CharField(max_length=64, null=True)),
                ('post_code', models.CharField(max_length=64, null=True)),
                ('phone_number', models.CharField(max_length=64, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('preferred_contact_type', models.CharField(choices=[('email', 'email'), ('phone', 'phone')], max_length=64, null=True)),
                ('additional_info', models.TextField(null=True)),
                ('investments', models.ManyToManyField(to='rep.InvestmentProject')),
            ],
        ),
        migrations.CreateModel(
            name='SalesPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('nickname', models.CharField(max_length=64)),
                ('clients', models.ManyToManyField(to='crm.Client')),
                ('investments', models.ManyToManyField(to='rep.InvestmentProject')),
                ('pricingplans', models.ManyToManyField(to='rep.PricingPlan')),
                ('products', models.ManyToManyField(to='rep.Product')),
            ],
        ),
        migrations.CreateModel(
            name='SalesPersonProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_link', models.DateTimeField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rep.product')),
                ('salesperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.salesperson')),
            ],
        ),
        migrations.CreateModel(
            name='ClientProductThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_link', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rep.product')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='products',
            field=models.ManyToManyField(through='crm.ClientProductThrough', to='rep.Product'),
        ),
    ]
