# Generated by Django 3.2.8 on 2021-10-29 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20211029_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesperson',
            name='pricingplans',
        ),
    ]
