# Generated by Django 3.2.8 on 2021-10-29 21:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_remove_salesperson_pricingplans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientproductthrough',
            name='date_of_link',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 29, 21, 38, 8, 555544, tzinfo=utc)),
        ),
    ]
