# Generated by Django 4.0 on 2022-01-10 17:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('reports', '0002_rename_pricing_name_pricingplan_pricing_plan_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('post_code', models.CharField(max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=255, null=True)),
                ('preferred_contact_type', models.CharField(choices=[('email', 'email'), ('phone', 'phone')], max_length=255, null=True)),
                ('additional_info', models.TextField(null=True)),
                ('investments', models.ManyToManyField(to='reports.InvestmentProject')),
            ],
        ),
        migrations.CreateModel(
            name='SalesPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('clients', models.ManyToManyField(to='cstmgmnt.Client')),
                ('investments', models.ManyToManyField(to='reports.InvestmentProject')),
            ],
        ),
        migrations.CreateModel(
            name='SalesPersonProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_link', models.DateTimeField(default=datetime.datetime(2022, 1, 10, 17, 48, 20, 360387, tzinfo=utc))),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.product')),
                ('salesperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cstmgmnt.salesperson')),
            ],
        ),
        migrations.AddField(
            model_name='salesperson',
            name='products',
            field=models.ManyToManyField(through='cstmgmnt.SalesPersonProduct', to='reports.Product'),
        ),
        migrations.AddField(
            model_name='salesperson',
            name='users',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.CreateModel(
            name='ClientProductThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_link', models.DateTimeField(default=datetime.datetime(2022, 1, 10, 17, 48, 20, 359387, tzinfo=utc))),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cstmgmnt.client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.product')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='products',
            field=models.ManyToManyField(through='cstmgmnt.ClientProductThrough', to='reports.Product'),
        ),
    ]
