# Generated by Django 3.2.8 on 2021-10-30 15:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('post_code', models.CharField(max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=255, null=True)),
                ('preferred_contact_type', models.CharField(choices=[('email', 'email'), ('phone', 'phone')], max_length=255, null=True)),
                ('additional_info', models.TextField(null=True)),
                ('investments', models.ManyToManyField(to='reports.InvestmentProject')),
            ],
        ),
        migrations.CreateModel(
            name='SalesPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('login', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=128, null=True)),
                ('clients', models.ManyToManyField(to='cstmgmnt.Client')),
                ('investments', models.ManyToManyField(to='reports.InvestmentProject')),
            ],
        ),
        migrations.CreateModel(
            name='SalesPersonProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_link', models.DateTimeField(default=datetime.datetime(2021, 10, 30, 15, 49, 5, 670413, tzinfo=utc))),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.product')),
                ('salesperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cstmgmnt.salesperson')),
            ],
        ),
        migrations.AddField(
            model_name='salesperson',
            name='products',
            field=models.ManyToManyField(through='cstmgmnt.SalesPersonProduct', to='reports.Product'),
        ),
        migrations.CreateModel(
            name='ClientProductThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_link', models.DateTimeField(default=datetime.datetime(2021, 10, 30, 15, 49, 5, 668419, tzinfo=utc))),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cstmgmnt.client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.product')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='products',
            field=models.ManyToManyField(through='cstmgmnt.ClientProductThrough', to='reports.Product'),
        ),
    ]
