# Generated by Django 3.2.8 on 2021-10-30 17:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cstmgmnt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesperson',
            name='full_name',
            field=models.CharField(default='<django.db.models.fields.CharField> <django.db.models.fields.CharField>', max_length=255),
        ),
        migrations.AlterField(
            model_name='clientproductthrough',
            name='date_of_link',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 30, 17, 4, 56, 8463, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='salespersonproduct',
            name='date_of_link',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 30, 17, 4, 56, 10522, tzinfo=utc)),
        ),
    ]
