# Generated by Django 4.0 on 2022-01-10 18:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cstmgmnt', '0002_alter_clientproductthrough_date_of_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientproductthrough',
            name='date_of_link',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 10, 18, 30, 13, 52244, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='salespersonproduct',
            name='date_of_link',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 10, 18, 30, 13, 53244, tzinfo=utc)),
        ),
    ]
