# Generated by Django 3.2.8 on 2021-11-02 21:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cstmgmnt', '0009_auto_20211102_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesperson',
            name='login',
        ),
        migrations.RemoveField(
            model_name='salesperson',
            name='password',
        ),
        migrations.AddField(
            model_name='salesperson',
            name='users',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientproductthrough',
            name='date_of_link',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 2, 21, 24, 59, 838586, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='salespersonproduct',
            name='date_of_link',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 2, 21, 24, 59, 841171, tzinfo=utc)),
        ),
    ]
