# Generated by Django 3.2.8 on 2021-11-11 19:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cstmgmnt', '0015_auto_20211111_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientproductthrough',
            name='date_of_link',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 11, 19, 46, 56, 616149, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='salespersonproduct',
            name='date_of_link',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 11, 19, 46, 56, 618260, tzinfo=utc)),
        ),
    ]
