# Generated by Django 3.2.8 on 2021-10-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricingplan',
            old_name='pricing_name',
            new_name='pricing_plan_code',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='symbol',
            new_name='code',
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='pricing_plan_name',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
