# Generated by Django 4.0 on 2022-01-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricingplan',
            old_name='pricing_name',
            new_name='pricing_plan_code',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='symbol',
            new_name='code',
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='pricing_plan_name',
            field=models.CharField(default='2022-01-10', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='finnish_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='balcony',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='loggia',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.CharField(choices=[('60%', '60%'), ('70%', '70%'), ('80%', '80%'), ('90%', '90%')], max_length=128),
        ),
    ]
