# Generated by Django 3.2.8 on 2021-11-01 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_investmentproject_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentproject',
            name='finnish_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='start_date',
            field=models.DateField(),
        ),
    ]
