# Generated by Django 3.2.8 on 2021-11-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20211111_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingplan',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
