# Generated by Django 3.2.8 on 2021-11-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_pricingplan_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.CharField(choices=[('60%', '60%'), ('70%', '70%'), ('80%', '80%'), ('90%', '90%')], max_length=128),
        ),
    ]
